<?php

/**
 * @file
 * Integrates the Mapify library with Drupal.
 */

/**
 * The vendor URL.
 */
define('MAPIFY_VENDOR_URL', 'http://etiennemartin.ca/mapify');

/**
 * The library URL.
 */
define('MAPIFY_LIBRARY_URL', 'https://github.com/etienne-martin/mapify');

/**
 * The minimum required version of jQuery needed.
 */
define('MAPIFY_MIN_JQUERY_VERSION', '1.7.2');

/**
 * Implements hook_libraries_info().
 */
function mapify_libraries_info() {
  $libraries = array();

  $libraries['mapify'] = array(
    'name' => t('Mapify'),
    'vendor url' => MAPIFY_VENDOR_URL,
    'download url' => MAPIFY_LIBRARY_URL . '/archive/master.zip',
    'version callback' => 'mapify_version',
    'files' => array(
      'css' => array(
        'build/jquery.mapify.css',
      ),
      'js' => array(
        'build/jquery.mapify.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_permission().
 */
function mapify_permission() {
  return array(
    'administer mapify' => array(
      'title' => t('Administer Mapify'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mapify_menu() {
  $items = array();

  $items['admin/config/user-interface/mapify'] = array(
    'title' => 'Mapify',
    'description' => 'Configure the Mapify module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mapify_settings_form'),
    'access arguments' => array('administer mapify'),
    'file' => 'mapify.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function mapify_init() {
  $load_mapify = TRUE;

  $paths_disable = variable_get('mapify_paths_disable', '');
  if ($paths_disable && drupal_match_path(current_path(), $paths_disable)) {
    $load_mapify = FALSE;
  }

  if ($load_mapify === TRUE) {
    libraries_load('mapify');
  }
}

/**
 * Version callback for the Mapify library.
 *
 * @return string|bool
 */
function mapify_version() {
  return TRUE;
}
